const { randomize } = require("./utils.js")

//generates a random number between 1 and 3 (inclusive)
//assigns it to the rivers variable
const createRivers = () => {
    const rivers = Math.floor(Math.random() * 3) + 1
    return rivers
}

//generates a random number between 1 and 2 (inclusive)
//assigns it to the mountains variable
const createMountains = () => {
    const mountains = Math.floor(Math.random() * 2) + 1
    return mountains
}

//generates a random number between 1 and 2 (inclusive)
//assigns it to the forests variable
const createForests = () => {
    const forests = Math.floor(Math.random() * 2) + 1
    return forests
}

//generates a random number between 1 and 4 (inclusive)
//assigns it to the plains variable
const createPlains = () => {
    const plains = Math.floor(Math.random() * 4) + 1
    return plains
}


const journeyMaker = () => {
    //Creates an empty array called "journey"
    const journey = []
    //creates an object called "areas" with keys for rivers (random value up to 3), forests (random value up to 2), mountains (random value up to 2), and plains (random value up to 4)
    const areas = {
        rivers: createRivers(),
        forests: createForests(),
        mountains: createMountains(),
        plains: createPlains()
    }

    //pushes the string "river" to the journey array a number of times equal to the number generated by the createRivers() function
    //then does the same for forest, mountain, and plains with their respective create functions.
    for (let riverNumber = 0; riverNumber < areas.rivers; riverNumber++) {
        journey.push("river")
    }

    for (let forestNumber = 0; forestNumber < areas.forests; forestNumber++) {
        journey.push("forest")
    }

    for (let mountainNumber = 0; mountainNumber < areas.mountain; mountainNumber++) {
        journey.push("mountain")
    }

    for (let plainNumber = 0; plainNumber < areas.plains; plainNumber++) {
        journey.push("plain")
    }
    //randomizes the order of the journey array, then returns the journey array
    return randomize(journey)
}

module.exports = {
    createRivers, createForests,
    createMountains, createPlains, journeyMaker
}
